feature/species-model
ruljin/CodersCamp2020.Project.NodeJS-Express-TypeScript.MyPlants pull request #1
Opened 2021-02-24 20:19 UTC by brzeczkowskaw

2021-02-24 20:58 UTC, Suegro24 requested changes
I think that name should be required and unique.

2021-02-25 15:30 UTC, Suegro24 approved these changes

2021-02-25 16:47 UTC, kami3la approved these changes

2021-02-26 16:27 UTC, Suegro24 reviewed
import from file `example` is pointless because we will delete this file as soon as possible
try to name models and schemas in singular

2021-02-26 21:42 UTC, Nilphym requested changes

2021-02-26 21:42 UTC, Nilphym commented on server/models/example.ts
> +export const mongoose = require('mongoose');
imo we should export mongoose in `server.ts`

2021-02-26 21:42 UTC, Nilphym commented on server/models/spieces.ts
> +module.exports = Species
we should use ES6 or CJS modules, not both
i would suggest using ES6

2021-02-26 21:42 UTC, Nilphym commented on server/models/spieces.ts
> +const Species = mongoose.model('specie', SpeciesSchema);
`specie`

2021-02-27 18:15 UTC, Nilphym approved these changes

2021-02-27 18:15 UTC, merged