Feature/notes controller
ruljin/CodersCamp2020.Project.NodeJS-Express-TypeScript.MyPlants pull request #19
Opened 2021-03-06 09:47 UTC by KonradMierzejewski

2021-03-06 11:49 UTC, kami3la requested changes
1. Use the eslint and make corrections
2. Why are you returning information about a comment and not a note?
3. You import model incorrectly, you forgot about the note model

2021-03-07 19:54 UTC, kami3la requested changes
1. You forgot to get a note by ID.
2. In the file 'server' change the path to singular, which is 'app.use (' / api / note ', noteController);'

2021-03-07 21:23 UTC, brzeczkowskaw requested changes
I think it should be 
app.use('/api/user/:id/note', noteController); 
in server.ts file, as every note should be assigned to specific user

2021-03-08 08:46 UTC, kami3la approved these changes

2021-03-08 10:55 UTC, brzeczkowskaw approved these changes

2021-03-08 14:14 UTC, Nilphym approved these changes

2021-03-08 18:12 UTC, merged