plant model added
ruljin/CodersCamp2020.Project.NodeJS-Express-TypeScript.MyPlants pull request #2
Opened 2021-02-24 20:37 UTC by brzeczkowskaw

commented out models to be added already

2021-02-24 20:55 UTC, Suegro24 requested changes
All the data should be required, name and latinName should be unique, image could have some default value

2021-02-25 15:30 UTC, Suegro24 approved these changes

2021-02-25 16:29 UTC, kami3la approved these changes

2021-02-26 21:47 UTC, Nilphym requested changes

2021-02-26 21:47 UTC, Nilphym commented on server/models/example.ts
> +export const mongoose = require('mongoose');
imo we should export mongoose in `server.ts`

2021-02-26 21:47 UTC, Nilphym commented on server/models/plant.ts
> +module.exports = Plant
we should use ES6 or CJS modules, not both
i would suggest using ES6

2021-02-26 21:47 UTC, Nilphym commented on server/models/plant.ts
> +//import {Toxicity} from './toxicity';
I don't think we should import comment nor toxicity
It's the same table in our erd diagram, I would include those in the same file

2021-02-27 18:14 UTC, Nilphym approved these changes

2021-02-27 18:14 UTC, merged