Feature/plant controller
ruljin/CodersCamp2020.Project.NodeJS-Express-TypeScript.MyPlants pull request #20
Opened 2021-03-06 11:40 UTC by brzeczkowskaw

2021-03-06 12:41 UTC, adax10 approved these changes

2021-03-07 18:05 UTC, Suegro24 approved these changes
You should delete comments

2021-03-08 14:31 UTC, Nilphym requested changes

2021-03-08 14:31 UTC, Nilphym commented on server/controllers/newPlantController.ts
> +});
Move those two to `plantController.ts` and delete the `newPlantController.ts` file.` Delete` endpoint does the same thing in both files so we don't need it.

2021-03-08 17:45 UTC, Nilphym approved these changes

2021-03-08 18:10 UTC, merged